OBJ     := ${SRC:.c=.o}

CC      := cc
CFLAGS  := -Wall -Werror -Wextra -I. -g

NAME    := libft.a

all:    ${NAME} ;

${NAME}: ${OBJ}
	ar rcs $@ ${OBJ}

%.o:
	${CC} ${CFLAGS} -c -o $@ ${@:.o=.c}

clean:
	rm -f ${OBJ}

fclean: clean
	rm -f ${NAME}

re:
	${MAKE} fclean
	${MAKE} all