/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   msh_lexer_init_fsm.c                               :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: vtestut <vtestut@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/12/06 18:54:59 by vtestut           #+#    #+#             */
/*   Updated: 2023/12/06 18:56:44 by vtestut          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "lexer.h"

static void	init_fsm_1(int table[LS_FINISHED + 1][LS_FINISHED + 1])
{
	table[LS_START][LS_START] = LS_PARSE_ERROR;
	table[LS_START][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_START][LS_WORD] = LS_WORD;
	table[LS_START][LS_NUMBER] = LS_NUMBER;
	table[LS_START][LS_SEPARATOR] = LS_PARSING;
	table[LS_START][LS_SQUOTE] = LS_SQUOTE;
	table[LS_START][LS_DQUOTE] = LS_DQUOTE;
	table[LS_START][LS_PIPE] = LS_PARSE_ERROR;
	table[LS_START][LS_REDIRECT_RIGHT] = LS_PARSE_ERROR;
	table[LS_START][LS_AREDIRECT_RIGHT] = LS_PARSE_ERROR;
	table[LS_START][LS_REDIRECT_LEFT] = LS_REDIRECT_LEFT;
	table[LS_START][LS_HEREDOC] = LS_PARSE_ERROR;
	table[LS_START][LS_PARSE_ERROR] = LS_PARSE_ERROR;
	table[LS_START][LS_FINISHED] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_START] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_WORD] = LS_WORD;
	table[LS_PARSING][LS_NUMBER] = LS_NUMBER;
	table[LS_PARSING][LS_SEPARATOR] = LS_SEPARATOR;
	table[LS_PARSING][LS_SQUOTE] = LS_SQUOTE;
	table[LS_PARSING][LS_DQUOTE] = LS_DQUOTE;
	table[LS_PARSING][LS_PIPE] = LS_PIPE;
	table[LS_PARSING][LS_REDIRECT_RIGHT] = LS_REDIRECT_RIGHT;
	table[LS_PARSING][LS_AREDIRECT_RIGHT] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_REDIRECT_LEFT] = LS_REDIRECT_LEFT;
}

static void	init_fsm_2(int table[LS_FINISHED + 1][LS_FINISHED + 1])
{
	table[LS_PARSING][LS_HEREDOC] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_PARSE_ERROR] = LS_PARSE_ERROR;
	table[LS_PARSING][LS_FINISHED] = LS_FINISHED;
	table[LS_WORD][LS_START] = LS_PARSE_ERROR;
	table[LS_WORD][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_WORD][LS_WORD] = LS_WORD;
	table[LS_WORD][LS_NUMBER] = LS_WORD;
	table[LS_WORD][LS_SEPARATOR] = LS_PARSING;
	table[LS_WORD][LS_SQUOTE] = LS_PARSING;
	table[LS_WORD][LS_DQUOTE] = LS_PARSING;
	table[LS_WORD][LS_PIPE] = LS_PARSING;
	table[LS_WORD][LS_REDIRECT_RIGHT] = LS_PARSING;
	table[LS_WORD][LS_AREDIRECT_RIGHT] = LS_PARSING;
	table[LS_WORD][LS_REDIRECT_LEFT] = LS_PARSING;
	table[LS_WORD][LS_HEREDOC] = LS_PARSING;
	table[LS_WORD][LS_PARSE_ERROR] = LS_PARSE_ERROR;
	table[LS_WORD][LS_FINISHED] = LS_FINISHED;
	table[LS_NUMBER][LS_START] = LS_PARSE_ERROR;
	table[LS_NUMBER][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_NUMBER][LS_WORD] = LS_WORD;
	table[LS_NUMBER][LS_NUMBER] = LS_NUMBER;
	table[LS_NUMBER][LS_SEPARATOR] = LS_PARSING;
	table[LS_NUMBER][LS_SQUOTE] = LS_PARSING;
	table[LS_NUMBER][LS_DQUOTE] = LS_PARSING;
	table[LS_NUMBER][LS_PIPE] = LS_PARSING;
}

static void	init_fsm_3(int table[LS_FINISHED + 1][LS_FINISHED + 1])
{
	table[LS_NUMBER][LS_REDIRECT_RIGHT] = LS_PARSING;
	table[LS_NUMBER][LS_AREDIRECT_RIGHT] = LS_PARSING;
	table[LS_NUMBER][LS_REDIRECT_LEFT] = LS_PARSING;
	table[LS_NUMBER][LS_HEREDOC] = LS_HEREDOC;
	table[LS_NUMBER][LS_PARSE_ERROR] = LS_PARSE_ERROR;
	table[LS_NUMBER][LS_FINISHED] = LS_FINISHED;
	table[LS_SEPARATOR][LS_START] = LS_PARSE_ERROR;
	table[LS_SEPARATOR][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_SEPARATOR][LS_WORD] = LS_PARSING;
	table[LS_SEPARATOR][LS_NUMBER] = LS_PARSING;
	table[LS_SEPARATOR][LS_SEPARATOR] = LS_PARSING;
	table[LS_SEPARATOR][LS_SQUOTE] = LS_PARSING;
	table[LS_SEPARATOR][LS_DQUOTE] = LS_PARSING;
	table[LS_SEPARATOR][LS_PIPE] = LS_PARSING;
	table[LS_SEPARATOR][LS_REDIRECT_RIGHT] = LS_PARSING;
	table[LS_SEPARATOR][LS_AREDIRECT_RIGHT] = LS_PARSING;
	table[LS_SEPARATOR][LS_REDIRECT_LEFT] = LS_PARSING;
	table[LS_SEPARATOR][LS_HEREDOC] = LS_PARSING;
	table[LS_SEPARATOR][LS_PARSE_ERROR] = LS_PARSE_ERROR;
	table[LS_SEPARATOR][LS_FINISHED] = LS_FINISHED;
	table[LS_SQUOTE][LS_START] = LS_PARSE_ERROR;
	table[LS_SQUOTE][LS_PARSING] = LS_PARSE_ERROR;
	table[LS_SQUOTE][LS_WORD] = LS_SQUOTE;
	table[LS_SQUOTE][LS_NUMBER] = LS_SQUOTE;
	table[LS_SQUOTE][LS_SEPARATOR] = LS_SQUOTE;
}

// static void	init_fsm_4(int table[LS_FINISHED + 1][LS_FINISHED + 1])
// {
// 	table[LS_SQUOTE][LS_SQUOTE] = LS_PARSING;
// 	table[LS_SQUOTE][LS_DQUOTE] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_PIPE] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_REDIRECT_RIGHT] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_AREDIRECT_RIGHT] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_REDIRECT_LEFT] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_HEREDOC] = LS_SQUOTE;
// 	table[LS_SQUOTE][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_SQUOTE][LS_FINISHED] = LS_PARSE_ERROR;
// 	table[LS_DQUOTE][LS_START] = LS_PARSE_ERROR;
// 	table[LS_DQUOTE][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_DQUOTE][LS_WORD] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_NUMBER] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_SEPARATOR] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_SQUOTE] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_DQUOTE] = LS_PARSING;
// 	table[LS_DQUOTE][LS_PIPE] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_REDIRECT_RIGHT] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_AREDIRECT_RIGHT] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_REDIRECT_LEFT] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_HEREDOC] = LS_DQUOTE;
// 	table[LS_DQUOTE][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_DQUOTE][LS_FINISHED] = LS_PARSE_ERROR;
// 	table[LS_PIPE][LS_START] = LS_PARSE_ERROR;
// 	table[LS_PIPE][LS_PARSING] = LS_PARSE_ERROR;
// }

// static void	init_fsm_5(int table[LS_FINISHED + 1][LS_FINISHED + 1])
// {
// 	table[LS_PIPE][LS_WORD] = LS_PARSING;
// 	table[LS_PIPE][LS_NUMBER] = LS_PARSING;
// 	table[LS_PIPE][LS_SEPARATOR] = LS_PARSING;
// 	table[LS_PIPE][LS_SQUOTE] = LS_PARSING;
// 	table[LS_PIPE][LS_DQUOTE] = LS_PARSING;
// 	table[LS_PIPE][LS_PIPE] = LS_PARSE_ERROR;
// 	table[LS_PIPE][LS_REDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_PIPE][LS_AREDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_PIPE][LS_REDIRECT_LEFT] = LS_PARSING;
// 	table[LS_PIPE][LS_HEREDOC] = LS_PARSING;
// 	table[LS_PIPE][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_PIPE][LS_FINISHED] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_RIGHT][LS_START] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_RIGHT][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_RIGHT][LS_WORD] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_NUMBER] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_SEPARATOR] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_SQUOTE] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_DQUOTE] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_PIPE] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_REDIRECT_RIGHT] = LS_AREDIRECT_RIGHT;
// 	table[LS_REDIRECT_RIGHT][LS_AREDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_REDIRECT_LEFT] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_HEREDOC] = LS_PARSING;
// 	table[LS_REDIRECT_RIGHT][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// }

// static void	init_fsm_6(int table[LS_FINISHED + 1][LS_FINISHED + 1])
// {
// 	table[LS_REDIRECT_RIGHT][LS_FINISHED] = LS_FINISHED;
// 	table[LS_AREDIRECT_RIGHT][LS_START] = LS_PARSE_ERROR;
// 	table[LS_AREDIRECT_RIGHT][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_AREDIRECT_RIGHT][LS_WORD] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_NUMBER] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_SEPARATOR] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_SQUOTE] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_DQUOTE] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_PIPE] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_REDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_AREDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_REDIRECT_LEFT] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_HEREDOC] = LS_PARSING;
// 	table[LS_AREDIRECT_RIGHT][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_AREDIRECT_RIGHT][LS_FINISHED] = LS_FINISHED;
// 	table[LS_REDIRECT_LEFT][LS_START] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_LEFT][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_LEFT][LS_WORD] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_NUMBER] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_SEPARATOR] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_SQUOTE] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_DQUOTE] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_PIPE] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_REDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_AREDIRECT_RIGHT] = LS_PARSING;
// }

// static void	init_fsm_7(int table[LS_FINISHED + 1][LS_FINISHED + 1])
// {
// 	table[LS_REDIRECT_LEFT][LS_REDIRECT_LEFT] = LS_HEREDOC;
// 	table[LS_REDIRECT_LEFT][LS_HEREDOC] = LS_PARSING;
// 	table[LS_REDIRECT_LEFT][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_REDIRECT_LEFT][LS_FINISHED] = LS_FINISHED;
// 	table[LS_HEREDOC][LS_START] = LS_PARSE_ERROR;
// 	table[LS_HEREDOC][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_HEREDOC][LS_WORD] = LS_PARSING;
// 	table[LS_HEREDOC][LS_NUMBER] = LS_PARSING;
// 	table[LS_HEREDOC][LS_SEPARATOR] = LS_PARSING;
// 	table[LS_HEREDOC][LS_SQUOTE] = LS_PARSING;
// 	table[LS_HEREDOC][LS_DQUOTE] = LS_PARSING;
// 	table[LS_HEREDOC][LS_PIPE] = LS_PARSING;
// 	table[LS_HEREDOC][LS_REDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_HEREDOC][LS_AREDIRECT_RIGHT] = LS_PARSING;
// 	table[LS_HEREDOC][LS_REDIRECT_LEFT] = LS_PARSING;
// 	table[LS_HEREDOC][LS_HEREDOC] = LS_PARSING;
// 	table[LS_HEREDOC][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_HEREDOC][LS_FINISHED] = LS_FINISHED;
// 	table[LS_PARSE_ERROR][LS_START] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_WORD] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_NUMBER] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_SEPARATOR] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_SQUOTE] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_DQUOTE] = LS_PARSE_ERROR;
// }

// static void	init_fsm_8(int table[LS_FINISHED + 1][LS_FINISHED + 1])
// {
// 	table[LS_PARSE_ERROR][LS_PIPE] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_REDIRECT_RIGHT] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_AREDIRECT_RIGHT] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_REDIRECT_LEFT] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_HEREDOC] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_PARSE_ERROR][LS_FINISHED] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_START] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_PARSING] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_WORD] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_NUMBER] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_SEPARATOR] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_SQUOTE] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_DQUOTE] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_PIPE] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_REDIRECT_RIGHT] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_AREDIRECT_RIGHT] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_REDIRECT_LEFT] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_HEREDOC] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_PARSE_ERROR] = LS_PARSE_ERROR;
// 	table[LS_FINISHED][LS_FINISHED] = LS_PARSE_ERROR;
// }

void	msh_lexer_init_fsm(int table[LS_FINISHED + 1][LS_FINISHED + 1])
{
	init_fsm_1(table);
	init_fsm_2(table);
	init_fsm_3(table);
	init_fsm_4(table);
	init_fsm_5(table);
	init_fsm_6(table);
	init_fsm_7(table);
	init_fsm_8(table);
}
